### ISSUE TITLE
Wrong documentation for the demo server

### ISSUE THREAD

**Issue by bortzmeyer** [private-octopus/picoquic#1091]
`./picoquicdemo -h`says ' -l file               Log file, Log to stdout if file = "n". No logging if absent'. But using `-l n` logs to a file named `n` instead.

See also #1055.

**Comment by huitema** [comment]
@bortzmeyer Thanks for filing the issue. This is being fixed in PR #1094.

The issue appeared after the work on unified logging, which simplified the API for logging. Before that, the application opened the log files itself, but after the fix it merely calls the API `picoquic_set_textlog()`. And the implementation of the API dropped the support for "log to stdout".

Note the the PR replaces the test `file = "n"` by `file = "-"`, which is more in line with common practice.
