### ISSUE TITLE
Is there any way to disable packet encrytion? 

### ISSUE THREAD

**Issue by Deviiiiant** [private-octopus/picoquic#1120]
Hi, I am reseraching quic encryption performance and intended to measure the quic encyrption overhead. Is it doable to disable packet protection?

**Comment by huitema** [comment]
There is no option to disable encryption, since encryption is pretty much a defining feature of QUIC. But you can certainly modify your copy of the code.

**Comment by huitema** [comment]
@Deviiiiant: In PR #1090, @iriszero mentioned that the cost of the encryption calls was "18.5% on the server and 11.0% on the client", the bulk of the CPU time being spent in the calls to UDP "sendmsg" and "recvmsg". The overall performance more than doubled since, after implementing UDP GSO and tuning the pacing algorithm. You may want to replicate the measurements reported in PR #1090, tracing the fraction of the CPU cost in four specific functions:

* Packet protection (encryption): calls to `picoquic_aead_encrypt_generic` or `picoquic_aead_encrypt_mp` in function `picoquic_protect_packet` in `sender.c`
* Header protection (encryption of packet sequence number and header flags): calls to `picoquic_pn_encrypt` in function `picoquic_protect_packet` in `sender.c`
* Removing header protection: calls to `picoquic_remove_header_protection` in `packet.c`
* Removing packet protection: calls to function `picoquic_remove_packet_protection` in `packet.c`

It would certainly be interesting to document these costs.

**Comment by Deviiiiant** [comment]
Thank you so much for all information you provided!

**Comment by huitema** [comment]
Considering this solved for now.
