### ISSUE TITLE
Test nat_attack fails

### ISSUE THREAD

**Issue by IvanNardi** [private-octopus/picoquic#1122]
It seems that with current master the "nat_attack" test fails.
The other tests are fine

```
ivan@ivan-Latitude-E6540:~/svnrepos/picoquic(master)$ ./picoquic_ct nat_attack
Starting test number 85, nat_attack
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
oquic/picoquic/packet.c:1751 [picoquic_find_incoming_path]: Cannot create new path for incoming packet
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
[...]
quic/picoquic/quicctx.c:1471 [picoquic_find_path_by_address]: Could not find path
quictest/netperf_test.c:618 [nat_attack_loop]: To many loops 100001
    Fails, error: -1.
Failed test(s): nat_attack 
```
Everything was fine until db3e350a
Tested on Ubuntu 20.04
Let me know if you need further information

**Comment by huitema** [comment]
@IvanNardi The code in "sock_loop.c" is not used in the nat_attack test, so there has to be some other reason.

This points to an issue with code integration. I have to port the tests from Travis CI to Github Actions, so they can run again, and verify that all tests pass on Ubuntu.

**Comment by IvanNardi** [comment]
> @IvanNardi The code in "sock_loop.c" is not used in the nat_attack test, so there has to be some other reason.
> 
> This points to an issue with code integration. I have to port the tests from Travis CI to Github Actions, so they can run again, and verify that all tests pass on Ubuntu.

Reading your reply, I noticed I was misleading: with db3e350 everything is still fine; I don't know which later commit introduced the regression
Very sorry for the confusion

**Comment by huitema** [comment]
@IvanNardi I just started Pr #1123 to add the "CITests" action on GitHub. I am not a big expert on GitHub Actions, and I could use help there!

**Comment by huitema** [comment]
Heisenbug alert! I tried reproducing on an Ubuntu VM and could not -- just completes fine. But then, as you can see, I do get a repro with the Github action script. Also, on some runs on the Ubuntu VM, the "nat_rebiding_stress" fails (typo for nat rebinding).  In the past, this random behavior was linked to variations in the random number generator on different platforms. I will check that.

These tests both stress the NAT rebinding functionality. The warning in `picoquic_find_path_by_address` is expected during NAT stress tests, because the code will only manage a limited number of paths, much lower than the number of addresses invented by the attacking NAT. The goal of the stress is to verify that the session recovers when the attack stops, but this is always a risky proposition, since an attack that persist long enough will eventually break the connection.

**Comment by huitema** [comment]
Looking at the code, the NAT Attack test was disabled on Windows because the test results were not consistent. I will disable it on Linux as well as part of PR #1123. I think the code path is already covered by the "nat rebinding stress". If not, we have to fix the nat attack test to make it consistent, and then reinstate it.
