### ISSUE TITLE
Signal that stream is closed

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#1210]
The application receives callback when all data of a stream is received, but not when all data from a stream have been acknowledged, or when the engine is done with a given stream. The function `picoquic_is_stream_acked()` computes that result, but is not exposed in the API.

In fact, we might need to have a function testing whether there is outstanding data for a stream, regardless of whether the stream is closed. This might be useful to synchronize the application.

**Comment by huitema** [comment]
The simple solution is to introduce a new call-back from transport to application. The engine would call back the application when a stream is "deleted", i.e., when all the data making up that stream has been acknowledged by the peer. There are however a couple of issues with that approach:

* It may provide application with a false sense of security. Transport level acknowledgements just mean that the data has been received and queued for processing, it does not mean that it has been processed, e.g. written to disk.
* it does not provide a solution for applications that send data without setting the FIN bit on a stream
* it may create additional callback traffic on applications like DoQ that use "one stream per message" design.

All of that is hypothetical. Some feedback would be good.

**Comment by victorstewart** [comment]
even though the primitive must be per stream, the real advantage i see here is being able to replicate TCP shutdown doing something like `picoquic_shutdown(cnx, 0);` where instead of hard closing the connection, it waits until all data sent on each stream has been ACKed before hard closing the connection and signaling any of the connection closed callback events.

**Comment by huitema** [comment]
To do this `picoquic_shutdown(cnx, <some_delay>);` properly, one needs some sync between server and client. Otherwise the client will open new streams, and the shutdown will be either dirty or postponed.

**Comment by huitema** [comment]
@victorstewart is there still interest? Or should we close this issue, and just decide that this function is better done at the application level?

If we did implement it, we would probably need some kind of policy parameter to decide what to do if the client opens new streams:
* maybe just immediately send "stop sending" and "reset" with an error code "server is closing", or
* accept the new stream and work on it until the shutdown delay elapses, or
* postpone the closing and issue some kind of callback.

**Comment by victorstewart** [comment]
i think close this. forgot about this.

it falls under the umbrella of "there's no way to actually accomplish an orderly shutdown because a connection could break at any moment for any reason".

thus an application must persist relevant data across connections to ever make any reliability guarantees. 

so i ended up implementing such a scheme and just hard closing all connections to hasten process turnover in the binary update situation.
