### ISSUE TITLE
Stream and path affinity

### ISSUE THREAD

**Issue by clarkzjw** [private-octopus/picoquic#1412]
Following https://github.com/private-octopus/picoquic/issues/1295#issuecomment-1288220135, I guess it's better to open a separate issue to discuss this.

So talking about the affinity of streams and paths, the motivation is to send specific streams over specific links in a multipath scenario. And maybe "links" or "interfaces" is a better alternative for "paths", since "path" in picoquic is a logical concept and new paths will be created if socket ports are different, even though the underlying physical links remain the same. 

My initial thoughts about implementing this are:
1. introduce a new `stream_ifindex` priority to `picoquic_stream_head_t` similar to `stream_priority`. And similar functions such as `int picoquic_set_stream_ifindex(picoquic_cnx_t* cnx, uint64_t stream_id, uint8_t ifindex)` is added to set the preferred interface index for streams.
2. In a multipath scenario, if the client calls `picoquic_set_stream_ifindex`, then the following packets belonging to this stream are sent out to the server via this interface, regardless of the path statistics, as long as there is any path available on this interface.
3. The server side remains the same, it just replies to the corresponding incoming IP and ports.

**Comment by huitema** [comment]
I think that you should keep the current definition of paths. The interface index is a local variable, designating the network card. You can very easily have two different paths using the same interface index, if they use different IP addresses.

If I implemented this, I would add a "path_affinity" variable to the stream context, holding either NULL or a pointer to the selected path context. Something like:
```
int picoquic_set_stream_path(connection, stream, struct sockaddr * source address, struct sockaddr * remote address, interface)
```
With the code finding the path that matches the specified addresses.

Then, I would modify `picoquic_find_ready_stream` to add a path argument, specifying the path on which the current packet is being sent, and only selecting available streams if they have no affinity (NULL) or affinity set to the current path.

You will need some way to remove the path affinity if a path breaks, is demoted, etc.

**Comment by huitema** [comment]
Of course, you have a separate problem of deciding paths on the server. I think it is best to decide that at the application level, rather than inside the picoquic code.

**Comment by clarkzjw** [comment]
> I think it is best to decide that at the application level, rather than inside the picoquic code.

By this, are you referring to the decision on the server side or the whole stream affinity problem?

> You can very easily have two different paths using the same interface index, if they use different IP addresses.

True, I didn't think about that.

> I would modify picoquic_find_ready_stream to add a path argument, specifying the path on which the current packet is being sent, and only selecting available streams if they have no affinity (NULL) or affinity set to the current path.

Since `picoquic_select_next_path` happens before `picoquic_find_ready_stream`, so the basic idea is to select the path first (either by current minRTT or future more complex path ranking), then find streams that should be sent on this path. So the "fairness" of sending different streams depends on the path selection mechanism, e.g., if a specific path gets a low rank (for whatever reason, either a high loss rate or high latency) and is selected less often, then the corresponding streams sent on this path get lower priorities, right?

**Comment by huitema** [comment]
Yes, I was referring to server side decisions.

When several paths are available, the path selection algorithm will try to send on each of them, according to their capacity, as measured by the congestion control algorithm. There is indeed one exception: if a path is considered in a dubious state because of too many packet losses, the algorithm will not select that path for sending data.

There is of course a tension between stream affinity and stream fairness. If you have a fast path and a slow path, a stream with affinity to the fast path will get more bandwidth and will be sent faster than one on the slow path. This is a tradeoff. Without affinity, a stream will have packets sent on both paths, which will cause delivery of stream data frames out of order, and thus increased queuing delays to wait for arrival from both paths before delivery. So affinity gives you lower delays, but no affinity gets you better throughput. The application has to choose wisely!

Back to the lossy path issue. Normally, picoquic will not send stream data on such path, because the risk of loss and increase delays is too high. We could make an exception for streams that have an affinity with the path, and send such data even if lossy condition is detected, as long as congestion control permits. The stream selection would then have to take into account a "lossy path" indication.

**Comment by clarkzjw** [comment]
> add a "path_affinity" variable to the stream context, holding either NULL or a pointer to the selected path context. Something like:
```
  int picoquic_set_stream_path(connection, stream, struct sockaddr * source address, struct sockaddr * remote address, interface)
```
> With the code finding the path that matches the specified addresses.

I assume this is only possible after the corresponding path is created and stored in `cnx->path`, otherwise it cannot find the required path for the stream. But when should be appropriate for the client to call `picoquic_set_stream_path`? After multipath probing finished? Or probe and create a new path inside `picoquic_set_stream_path` if the required path is not found?

Or, should the stream context just holds variables to `struct sockaddr * source address` and `struct sockaddr * remote address` and then compares them to `cnx->path[i]->peer_addr` and `cnx->path[i]->local_addr` in `picoquic_find_ready_stream`?

**Comment by huitema** [comment]
Yes, this will only happen after the path is created. Pretty hard to do it beforehand. In fact, pretty hard to make scheduling decisions before getting first some traffic on the path, evaluating its available bandwidth and RTT, etc.

We can debate whether the API should include a handle of the path (pointer to picoquic_path_t) or description of addresses. Maybe use a handle, and have another API to retrieve path handles. But I do not like handles too much, because that amounts to passing pointers around, and pointer-passing APIs are dangerous. An alternative would be some kind of unique path ID, but that's just as hard to manage as addresses.

**Comment by huitema** [comment]
Thinking about this again. The entries above discuss how to identify paths at the API. Assuming we solve that, the next issue is what exactly "affinity" means. The application makes a call setting an "affinity" with path X. What does that mean? The simplest implementation would be:

* when it comes to scheduling a packet on path X, apply regular stream scheduling, but ignore the streams that have set affinity for another path.

That's easy enough to implement, and it has the desired result of preserving the order of transmission: if stream affinity is set, the data will be sent only on that stream. The next question is, what to do if path X becomes unavailable. Should we:

* just delete the affinity, and transmit the data on whatever stream is available?
* or provide a signal to the application, something like "affinity is broken", for all streams that use to have an affinity with this path, so the application can make a decision?

Then there are also other issues, such as when a path slows down, or is affected by lots of losses. Should the application be notified? How?

And finally, there is the potential for redundancy. What if the stream data should be copied on multiple paths? Maybe with regular data on primary path, and redundancy or FEC sent on another path? Is that part of "affinity", or another API that comes after it?

**Comment by huitema** [comment]
Let's first resolve issue #1459, to expose path identifiers and path related events. Once we have callbacks for path events, the application can revisit the affinity sets after events like path deletion or change of path quality. That means we can have a very simple solution:
~~~
picoquic_set_stream_path(picoquic_cnx_t * cnx, void* path_handle, uint64_t stream_id)
~~~
With "path handle" being the identifier returned by the path related events.

The stack will automatically delete affinities if a stream is deleted.

**Comment by clarkzjw** [comment]
A related question, do you have plans in the future to make [`picoquic_select_next_path_mp`](https://github.com/private-octopus/picoquic/blob/master/picoquic/sender.c#L4411) modular/pluggable similar to allowing different congestion control algorithms?

**Comment by huitema** [comment]
Path affinity API was added in PR #1482:
```
int picoquic_set_stream_path_affinity(picoquic_cnx_t* cnx, uint64_t stream_id, uint64_t unique_path_id);
```
There is parallel support for getting the `unique_path_id` on which datagrams can be prepared, and new or modified API like:
```
int picoquic_mark_datagram_ready_path(picoquic_cnx_t* cnx, uint64_t unique_path_id, int is_path_ready);
uint8_t* picoquic_provide_datagram_buffer_ex(void* context, size_t length, picoquic_datagram_active_enum is_active);
```
I think this solves the issue.
