### ISSUE TITLE
Cubic does not stabilize throughput to 2Gbps bottleneck

### ISSUE THREAD

**Issue by alexj0l** [private-octopus/picoquic#1445]
<img width="578" alt="pico" src="https://user-images.githubusercontent.com/20671283/219877362-1f850d05-74e3-42e9-aa81-6e37833263d7.png">
The orange line is the throughput of Picoquicdemo at the outgoing interface of sender, while the other lines are some other QUIC implementations. The network has no added delay, no added loss but a bottleneck of 2000Mbit/s. When testing in a network without a bottleneck, Picoquic shows a throughput of 2.7Gbit/s (average over multiple runs). 
Picoquic has been run with `/home/user/quics/picoquic/picoquicdemo -n test -G <cc> -D <server> 4433 "*10:0:-:2000000000:0"`

**Comment by huitema** [comment]
This is an interesting issue, with three suspects: congestion control, flow control, and possibly some interaction of congestion control with CPU. It seems that the observed throughput remains in the band between 1750 and 2000 Mbps. This looks like what Cubic would do: on packet loss, the Cubic code in Picoquic drops the window to 7/8th of the previous value. But if this was only Cubic, we should observe a "saw tooth" pattern, and we see something else. The teeth of the line should go all the way to 2Gbps, but we see them falling short. Also, the line does not have the shape of cubic curves. 

Before we analyze further, let's answer these questions:

1) What is the latency of the link, and the RTT of the path?
2) How do you enforce the bottleneck bandwidth? Is this at the outgoing interface, or in the middle of the path? Are you dropping packets or merely queuing them? Are you applying ECN marks?
3) How do you measure the throughput of the outgoing interface? Is this some kind of averaging over time?

If possible, I would like to check whether the same pattern appears if we switch the CC to BBR. I would also like to see whether the bottleneck enforcement somehow causes spikes in CPU load, maybe because packet losses cause packets to be received "out of order".
