### ISSUE TITLE
Picoquic performance analysis 

### ISSUE THREAD

**Issue by Milind-Blaze** [private-octopus/picoquic#1649]
We have been trying to analyze Picoquic's performance and have some preliminary results that we would like to share. 

In this analysis, we look at the throughput, application level message latency and CPU usage of Picoquic and socket TCP provided by Linux. To do this, we use a simple client and server written using the Picoquic and the socket API in C++. The client and server are both run over localhost of a Linux machine.

We define/obtain latency, throughput and CPU usage as below

- **Latency**: This is the application level RTT. Here, a connection is initiated between the client and server. A timestamp is recorded (say $t_0$). The client immediately sends a request to the server requesting $m$ bytes of data. The server responds by sending a message consisting of $m$ random bytes of data back to the client. Once the client receives all the bytes, it is produces another timestamp (say $t_1$). Latency for this message is $t_1 - t_0$. This is repeated 100000 times and the mean latency is computed. This is repeated for $m =$ 10 KB, 100 KB, 1 MB.  
- **Throughput**: This is similar to the previous experiment but $m = $ 1 GB and throughput is computed as mean($\frac{m}{t_1 - t_0}$) over hundred such transfers.
- **CPU usage**: This is obtained using the top command to monitor the CPU usage (reported as how much of one core is used) periodically every 1s while running the throughput experiment above with the 1 GB file. The mean of all the resulting values is presented.

In the case of throughput and CPU measurement, the experiment was also repeated with a TC constraint that restricted the throughput to 100 Mbps. 

Note 1: In all the reported results, the standard deviation is reported in the brackets. 
Note 2: There is no HTTP in the server-client pair i.e the (+ HTTP) in the table below is a typo.

Please find the results below

<img width="913" alt="Screenshot 2024-03-06 at 17 11 19" src="https://github.com/private-octopus/picoquic/assets/25522467/a40a38ff-6f26-4825-8094-d924e4f9ef52">

Is this the expected performance of picoquic? Low latency is very important to our use case and any feedback on steps we can take to lower latency when using picoquic would be very welcome!

**Comment by huitema** [comment]
You are reporting a picoquic throughput of 2.2 +- 0.1 Gbps. That's about what I expect. The actual results depend on hardware, and other papers have reported performance between 2, 4 and 5 Gbps. There may be a problem with your configuration, with client and server running on the same core instead of 2 separate cores. I they were separate, I would expect the CPU consumption to hit close to 100% on either the server or the client, much like it does on TCP. Having just 40% for the server is strange; having 82% for server + client makes me suspect a single core setup.

TCP is of course faster, for a variety of reasons.The protocol work is done in kernel; some is done in the client thread context, but all the driver and interrupt processing may well be done on another core. Then, the app/kernel boundary is somewhat better organized for TCP. TCP does not bother with encryption, so you get lower CPU consumption for the same throughput. It would be interesting to repeat this analysis with TCP+TLS, which is a bit more comparable to QUIC.

Some of the difference in TC=100Mbps throughput may be due to the larger per packet overhead of QUIC. TCP overhead is IP(20) + TCP(20) = 40 -- 40/1500 = 2.7%; IP header + UDP (8 bytes) + QUIC-header (12) + QUIC checksum (16) + Stream Frame header (8) = 64 - 64/1500 = 4.3%. But there may be something else happening as well, with BBRv3 deliberately limiting the data rate to 98% of measured bandwidth in order to avoid queues.

The latency differences with 100K and 1MB are probably a side effect of the throughput differences. 1 MB in 3.26ms corresponds to 2.45 Gbps.

The performance that you measure are "in the ballpark", but could probably be improved. I did a round of optimization 2 years ago, it may be time to start a new one -- get a flame graph for a server and a client, see whether we have hot points, fix them, etc. But before we do that, we should verify that client and server are running on separate cores. Or, ideally, on separate machines.

By the way, we have a "Quic Perf" specification. Did you use that?

**Comment by davidfdzp** [comment]
It would be nice to see histograms of the measurements. Measuring the mean plus the standard deviation is useful when the distribution of the measurement is Gaussian, which could be the case for throughput, but probably not for latency, which is usually something like lognormally distributed. In that case, measuring percentiles 95 and 99.9 of latency would be better. Just a suggestion. Thank you for the data.
