### ISSUE TITLE
Document the use of picoquic in background thread.

### ISSUE THREAD

**Issue by talaltouseef** [private-octopus/picoquic#1667]
Hi,

I am writing a simple networked application using picoquic. There is a sender and a receiver. The sender will send some data periodically and the receiver will receive and process it (the receiver will not send any data back to the sender). I am planning on using the `picoquic_add_to_stream` API to send the data. The [documentation](https://github.com/private-octopus/picoquic/blob/master/doc/architecture.md#single-threaded-library) mentions that picoquic is not threadsafe. So, I cannot have a thread that periodically calls the `picoquic_add_to_stream` API and a separate thread that runs the `picoquic_packet_loop`. So, I am assuming that I have to call the `picoquic_add_to_stream` API, enter the `picoquic_packet_loop` to send the data, exit out of the `picoquic_packet_loop` and repeat to send data periodically. Is this the right approach? If so, how do I exit out of the `picoquic_packet_loop` after the data is sent? Or is there some other approach that I should use? It would be great if someone could help me out. Thanks!

**Comment by hfstco** [comment]
Hi @talaltouseef,

I wrote a split PEP implementation based on picoquic. It's not finished yet, but I will share it on GitHub in the near future. Maybe I can help you a little bit. 

> The [documentation](https://github.com/private-octopus/picoquic/blob/master/doc/architecture.md#single-threaded-library) mentions that picoquic is not threadsafe. So, I cannot have a thread that periodically calls the picoquic_add_to_stream API and a separate thread that runs the picoquic_packet_loop.

Of course, you can!? You only need to synchronise them correctly. My PEP implementation runs on (a) thread(s), which handles the incoming and outgoing data of the endpoints and writes/reads them into a pipe/buffer, and another thread is running picoquic, to transmit the data - from the pipes - between the PEPs. 

Some hints:
- Take care not to block the picoquic loop. Otherwise, you block everything.
- Run a custom picoquic network thread to wake up picoquic. (`picoquic_start_network_thread()`, `picoquic_wake_up_network_thread()`) 
- Synchronise your other threads to access picoquic.
Maybe @huitema can answer, which parts of picoquic are threadsafe. (ie. picoquic_add_to_stream, but I think it's not.)

> So, I am assuming that I have to call the picoquic_add_to_stream API, enter the picoquic_packet_loop to send the data, exit out of the picoquic_packet_loop and repeat to send data periodically.

I don't know if it is a good idea to exit picoquic_packet_loop. My picoquic loop runs "infinitely" and I wake it up (`picoquic_wake_up_network_thread()`) if there is more data to send. If you want to follow this approach I advise to take a loop on the [select timeout](https://github.com/private-octopus/picoquic/blob/75a85d633e72f36e261fed83b069ed3ef6d0cfed/picoquic/sockloop.c#L609) - you can wake it up with `picoquic_wake_up_network_thread()` - and the [idle timer](https://github.com/private-octopus/picoquic/blob/75a85d633e72f36e261fed83b069ed3ef6d0cfed/picoquic/picoquic.h#L673C63-L673C71) - if you don't send data all the time. 

> Is this the right approach? If so, how do I exit out of the picoquic_packet_loop after the data is sent? Or is there some other approach that I should use? It would be great if someone could help me out. Thanks!

I am not sure if my approach is the best one. But it works. :)

Best regards

PS: It's generally a good advise to take some time - or even more -  to study the [picoquic API](https://github.com/private-octopus/picoquic/blob/master/picoquic/picoquic.h#L673C63-L673C71). It will save you a lot of time. :)

**Comment by huitema** [comment]
Unless otherwise indicated, all the picoquic API defined in "picoquic.h" should be called from the thread running the picoquic_packet_loop.

In practice, there are two approaches: describe your application as an automaton that can progress based on feedback about the state of the connection; or, use queues to pass messages between the application thread (or threads) and the network thread. Most of the test applications, including "picoquicdemo" follow the automaton approach, but that limited.

I would very much like to add a communication model to the "custom packet loop", but I cannot do this myself for a couple of weeks. If someone else want to write a PR, I will be happy to review it. (And provide credits, of course.)

@hfstco is correct, you should definitely look at `picoquic_wake_up_network_thread()`. The general structure of the communication ought to be something like:

* From the application, post messages such as "open stream", "write to stream", etc.
* After posting the messages, call  `picoquic_wake_up_network_thread()` to make sure that the network loop is interrupted.
* In the `picoquic_packet_loop_wake_up` callback from the network loop, process your application's messages and translate them into calls to the picoquic API.

**Comment by huitema** [comment]
In PR #1742 I added a "background sample" that document the use of the background thread. I think that solves the issue. @talaltouseef please look at the code in `sample/sample_background.c` and reopen the issue or open another if you have suggestions for improvement, etc.
