### ISSUE TITLE
Getting PICOQUIC_ERROR_IDLE_TIMEOUT even though remote side is sending PINGs

### ISSUE THREAD

**Issue by TimEvens** [private-octopus/picoquic#1687]
While integrating https://github.com/quic-go/quic-go based client with picoquic, we ran into an issue where picoquic would close the connection due to PICOQUIC_ERROR_IDLE_TIMEOUT.  Both sides are set correctly for keep alvie and idle timeouts.  Both sides are sending PINGs as expected during idle periods.  Picoquic does receive and process the PING, but does not consider the ping as received data, resulting in in idle timeout kicking in.

**Comment by huitema** [comment]
This behavior is supposedly tested. In theory, picoquic does consider the ping as received data. Also in theory, there should not be anything special for Ping frames. For example, some implementation might decide to send MAX_DATA frames, and that should have the same effect. RFC 9000 says:

_"An endpoint restarts its idle timer when a packet from its peer is received and processed successfully. An endpoint also restarts its idle timer when sending an ack-eliciting packet if no other ack-eliciting packets have been sent since last receiving and processing a packet. Restarting this timer when sending a packet ensures that connections are not closed after new activity is initiated."_

On the receive side, picoquic does exactly that -- there is code to that effect in `picoquic_incoming_segment()` in `packet.c`. That code is generic, resets the timer if any packet is received. If we do have an issue, it may be on the send side, and that's what we need to check.

Obviously, the picoquic tests differ from the actual behavior of the QUIC GO client. I understand that you have a fix working in your fork. Before bringing in to the main branch, I would like to build a test that reproduces the QUIC GO behavior. How does it differ from what we test? What are the assumptions?

**Comment by TimEvens** [comment]
Turns out the root of the problem was related to our go code deadline.
