### ISSUE TITLE
feature request: add websocket example, aka rfc9220

### ISSUE THREAD

**Issue by liudongmiao** [private-octopus/picoquic#1691]
If this can be accepted, I could make a pr in picoquicdemo.
I mainly test it with nginx server (patched, not public yet).

**Comment by huitema** [comment]
RFC 9200 is the specification of OAuth in contrained environments. It would certainly be an useful addition to the toolkit.

Picoquicdemo is a demonstration tool, backed by libraries. I would like to understand how you would integrate OAuth with these libraries. Do you have a proposed design?

**Comment by liudongmiao** [comment]
@huitema Sorry for the type, the rfc is 9220, not 9200.
https://datatracker.ietf.org/doc/html/rfc9220

There is no browser support yet: https://chromestatus.com/feature/5080537855688704

**Comment by huitema** [comment]
Oh, I see! Yes, implementing RFC9220 looks like a good idea. It would for example running QUIC between a client and a proxy, and then setting up a TCP connection. If you want to develop that, please go on and I will review the code. But I have three requests:

* as much as possible, place the webproxy code in its own file, and organize the code so that it is linked "on demand". There are users of picoquic deploying their servers or applications on small devices, and we need to make sure that their images stay small.

* add an option to handle TCP sockets in the "socket loop", so we can keep the general architecture. (This is generally useful, I would be willing to help there.)

* and of course provide test files.

**Comment by liudongmiao** [comment]
Sorry, I'm closing this request as I switch to OpenSSL's quic implementations.
