### ISSUE TITLE
Wireshark packet traces detect UDP packets on alternate path and not QUIC

### ISSUE THREAD

**Issue by SupradhaBhat** [private-octopus/picoquic#1748]
We tried using the picoquic library with the following network namespace 
![Screenshot 2024-09-08 191708](https://github.com/user-attachments/assets/4ebee3b7-4ae6-444c-9b36-e1cbc450da4f)
When capturing packets via Wireshark on link 1 (the primary interface), we observe QUIC packets as expected. However, on link 2 (the alternate path), only UDP packets are captured—no QUIC packets appear in the trace. Is this the expected behavior, or should we be seeing QUIC packets on link 2 as well?

**Comment by huitema** [comment]
It is very hard to tell without having more information. The packets on link 1 will include the QUIC handshake, which wireshark can recognize easily -- the handshake uses packets with long headers. The packets on link 2 will only include packets of type 1RTT, with a short header. It is possible that wireshark does not recognize them as QUIC packets. That would be an issue with wireshark.

Also, picoquic does not provide wireshark with decryption keys by default -- that would be too much of a security hole, because anyone with machine access could grab these keys. To pass the keys, you have to set the option "-8" in the demo program.

For further debug, you may want to enable qlog capture on client and server. That would help understand whether the issue is with wireshark or with picoquic.

**Comment by hfstco** [comment]
Wireshark struggles to recognise QUIC _MP__ frames if they aren't decrypted. After injecting the TLS secrets everything works fine. Just export the TLS secrets, like @huitema explained above, and you should be fine.

Results were captured on remote side.
![IMG_0033](https://github.com/user-attachments/assets/77f0b0b3-c30b-4cb5-bfd6-5e22e97be6a6)

[multipath.zip](https://github.com/user-attachments/files/16929146/multipath.zip)

https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-quic.c
If I understand the Wireshark code correctly, it only checks whether MP has been negotiated in the transport parameters. Then it looks for _MP__ frames, which, as you can see in the pcap without TLS secrets injected, are not visible. But I only briefly flew over the code.

**Comment by SupradhaBhat** [comment]
I tried adding -8 flag, yet, the Wireshark capture shows UDP on one interface and QUIC on the other. We also tried capturing packets using tcpdump, but we observed that packets captured on both interfaces are UDP. 
Following is a screenshot of the qlogs captured on the client side 
![WhatsApp Image 2024-09-27 at 18 29 29_e7b420c8](https://github.com/user-attachments/assets/a3b9f37d-c0b6-4c98-9705-952f0d8ec983)

**Comment by huitema** [comment]
The wireshark issue is an issue with wireshark. You should file that with wireshark. Or maybe there is already an issue filed there. @alagoutte and/or @IvanNardi might be able to help you.

**Comment by huitema** [comment]
The qlog appears nominal, showing traffic flowing on both paths.

**Comment by IvanNardi** [comment]
> The wireshark issue is an issue with wireshark. You should file that with wireshark. Or maybe there is already an issue filed there. @alagoutte and/or @IvanNardi might be able to help you.

@SupradhaBhat, could you open a ticket in Wireshark repository attaching pcap *AND* keylog files, please?

**Comment by SupradhaBhat** [comment]
@huitema @hfstco sorry for getting back at this late
could you please guide me on where will the keylog files be stored once i set the -8 option in the demo program

**Comment by hfstco** [comment]
Simply set the SSLKEYLOGFILE environment variable. It specifies where your TLS keys are stored.

e.g.: 
SSLKEYLOGFILE=tls.keys ./picoquicdemo ...
OR
export SSLKEYLOGFILE=tls.keys
./picoquicdemo
