### ISSUE TITLE
The mix of host and network byte order

### ISSUE THREAD

**Issue by alexrabi** [private-octopus/picoquic#1802]
As discussed in issue #1778, there is currently some ambiguity surrounding whether the port numbers in the application should be in host order or in network order. The APIs involving port numbers should be made consistent and clear.

**Comment by huitema** [comment]
I think the goal should be to leave all "sockaddr" structures used in the stack in host order, and only convert to network order at the latest moment, i.e., when making actual socket code. The good news is that we are almost there. The "local" and "peer" addresses in the "path" structures are in host order.
Among the exceptions:

1) the "preferred address" transport parameter is stored in network order. This should be fixed, because it is mostly used to set path addresses.
2) the address-to-text utility functions in util.c, qlog.c and logger.c convert the port number to network order before printing it.
3) the port-blocked logic converts its input from network to host order.
4) the "incoming path" function compares assumes network order for the incoming addresses.

These addresses are exposed in a set of API: picoquic_get_peer_addr, picoquic_get_local_addr, picoquic_set_local_addr, picoquic_incoming_packet_ex, picoquic_prepare_next_packet_ex,  picoquic_notify_destination_unreachable, picoquic_notify_destination_unreachable_by_cnxid, picoquic_create_cnx, picoquic_create_client_cnx, picoquic_probe_new_path, picoquic_probe_new_path_ex, picoquic_get_path_addr.

We need to verify that all these API assume host order, and that the "socket loop" respects that order when communicating with the stack.

**Comment by huitema** [comment]
This should be fixed in PR #1808
