### ISSUE TITLE
picoquic replies on the wrong address

### ISSUE THREAD

**Issue by dbavatar** [private-octopus/picoquic#33]
A server can, and especially in the case of ipv6 does have multiple addresses. picoquic will have to keep track of which address it is serving data from and reply using that address. I hacked up something quickly for testing v4, but the basic idea is to use cmsg pktinfo to get/set the address

https://github.com/dbavatar/picoquic/commit/f1db0bd564f2a1ab1c4b93881a4ba81db482745f

**Comment by huitema** [comment]
Possible solution is to bind one socket for each of the local addresses. But this is messy, because we have then to keep track of address assignment. Is there a good alternative, easy to port on Windows and multiple Unix variants?

**Comment by huitema** [comment]
We could try something using IP_PKTINFO/IPV6_PKT_INFO, recvmsg()/WSARecvMsg(), and sendmsg()/WSASendMsg(). But I don't know whether that's much better than using multiple socket.

**Comment by dbavatar** [comment]
I don't think multiple sockets are a good idea, doesn't scale to a large number of IP's. Take for example binding to a /64 v6 address. I think the right thing to do is to record the address tuple of the packet in the connection context, then use that modulo RFC rules around address migration for both client and server.

**Comment by huitema** [comment]
Even with a /64, the QUIC server is only supposed to serve a few addresses, those that are advertised in the A and AAAA records. But yes, the recording of addresses in the context looks right.

One more thing. QUIC may not be authorized to answer to all the addresses configured on the device. For example, servers are supposed to not answer to temporary IPv6 addresses, because doing so reveals the link between the service host and a the temporary address, and thus enables tracking. Similarly, clients are supposed to use the temporary addresses exclusively, if they are configured. This will require some kind of configuration.

**Comment by huitema** [comment]
Working on it. Started by moving the socket code to its own file in the library and writing a unit test. There was actually a bug introduced by PR #32 -- we forgot to also update the function that the server used to send packets on the socket matching the client's IP protocol. As a result, the server did not work with IPv4. Oops. The new unit test ensures that kind of bug will not repeat.

**Comment by huitema** [comment]
Turns out to be a rather large development. The Windows socket code can now obtain the incoming destination address through select, and set the source address and interface in the server sending code. This is now in the library, tested with appropriate unit test. Still has to be verified in Unix and added in the demo, but we are getting there...

**Comment by huitema** [comment]
Debugging the Linux code. Still something to fix...

**Comment by huitema** [comment]
Code is fixed. Still need to call the proper API in the demo program.

**Comment by huitema** [comment]
And the demo and stack are now getting the parameters. The "local" address is acquired on the first incoming packet, and is then use in the sendmsg API to fix the outcoming source address.
