### ISSUE TITLE
Call `picoquic_prepare_packet` in a loop

### ISSUE THREAD

**Issue by bkchr** [private-octopus/picoquic#463]
I think we need to update the demo [here](https://github.com/private-octopus/picoquic/blob/f9798134f3e98ee4ad39d120e9f451b7edd9856b/picoquicfirst/picoquicdemo.c#L532).
We should call `picoquic_prepare_packet` in a loop until all packets for a connection are send. I think that this is one of the main issues, I have seen for connections with multiple streams. The main stream was generating a lot of data and the other streams did not get any real change to send something.
I built the rust bindings, based on your demo. So, I imported this problem upstream^^

**Comment by bkchr** [comment]
Hmm that still did not really solved my problem. I need to take another look at it.
If I have multiple streams and do not add any data between the `prepare_packet` calls, all the data of all streams should be send?

**Comment by bkchr** [comment]
Is the stress test using multiple streams?
I added another stream to my application today and have the feeling that it made everything more fragile.

Multiple concurrent steams that are sending data, should be doable with quic?

**Comment by huitema** [comment]
I have been using multiple streams in the demo server for some time, and there was no obvious problem.  The stress test defaults to 4 streams max per connection; that number is really easy to change. However, the streams are drained in order, and the test servers just post a variable size message on each stream. I don't think we have a test in which the streams are just continuing, and that would certainly be a good addition to the test cases -- or to the stress behavior.

**Comment by huitema** [comment]
The loop is written with a "receive first" logic: process all the packets that are already received through the sockets, or none if there is nothing ready; then prepare packets for the next connection in order. There is a next wake time for each connection, based on data queued, flow control, etc. The connections are then polled in order of the wake time. There could obviously be a bug, so that a given connection would always ask to be awaken "right now".

**Comment by bkchr** [comment]
If I poll the connections based on their wake time, what happens if a connection has more data than what fits into one package?
As I understand it, the connection is scheduled to be woken up at "current_time", so that theoretically I will be requested to call picoquic immediately.
Now, when I restart the loop, I will begin with polling the streams again to see if they want to send something. The streams can send data from multiple threads. So, if stream 1 wants to send data  again, the other steams will not get any chance to send their data(if stream 1 is filling up one package again). Because of that, I thought that calling `prepare_packet` again, until no package is returned could enable the other streams to send their data.

**Comment by huitema** [comment]
I should check that part of the code. The goal is that if connections have the same wake time they get polled in turn. If a connection is reinserted with "the same time", it should be reinserted after the ones already queued at that time.

**Comment by bkchr** [comment]
Okay, I looked into this again. Calling `prepare_packet` multiple times is not the correct solution, as you already mentioned.
I looked into the implementation of quic go. They use an extra list of streams that want to send data, each new stream is added to the end of this list. Thus, they make sure that each stream can send data. In picoquic we always look at the first stream, when we want to send something. This brings us to this situation, that when stream 1 is sending continously, the other streams do not get any chance to send any data. We should introduce a similar list. The current implementation clearly puts a priorization for streams with lower ids.

I also tested in my application to put the video into the last stream I create and that clearly improved the performance of the other streams.

**Comment by huitema** [comment]
Pull model would be a "ready to send" call back? Yes, we could do that, maybe as just another option in the current callback. It would be called if the sending loop finds itself blocked with no data.

**Comment by bkchr** [comment]
I would just have added a second list `active_streams` or `streams_want_to_send`. That just contains the streams that want to send data in the order they need to be fetched. If a stream wants to send data and is not on the list, it is added to the end of the list. If a stream is able to send data (first of the list) and there is still data to send, it is added to the end again.
So you can just keep the normal list. Like we have for the connections.

**Comment by bkchr** [comment]
@huitema if I call `prepare_packet` multiple times in a loop, do I work around the congestion protocol?

**Comment by huitema** [comment]
I will address the performance issues later, and the rotation in PR #465 should just work. But I am still concerned with the various congestion and flow control issues:

1) We have both congestion control and flow control with the scope of the connection. This limits how much data can be sent on any stream.

2) We have stream ID control also at the scope of the connection. This limits how many streams can be open at a given time.

3) We have flow control at the level of the stream. This limits how much data can be sent on a given stream.

We could provide full visibility into the state of the transport, and in fact maybe we should. How much data is queued or sent per stream, how many streams can be opened, whether the stream or the connection are blocked by flow control or congestion control, the largest stream ID authorized by the peer, all that could be exposed through the API. Maybe we should just go ahead and expose it, since that data is readily available in the connection state. But then, I doubt that the average application developer will bother managing that level of complexity.

The approach so far has been to not bother the application with such details. It can open as many streams that it wants, and queue as much data as it wants. The transport will just make sure to not open more streams or send more data than allowed by the peer. I think we could have a callback when all the data queued on one stream has been sent. That should be sufficient in most cases.

**Comment by huitema** [comment]
By the way, no, calling `prepare-packet` multiple times will not change the state of congestion control. It only changes when acknowledgements or flow control messages are received from the peer.

**Comment by bkchr** [comment]
I don't see the problem, when the flow control limits how much data can be send on connection level. We just change the order we pull the data out of the streams, the maximum amount can still be limited by the flow control.

So calling `prepare_packet` multiple times could violate some constraints? Maybe we should make sure that this it not possible. If a connection is not allowed to send any data `prepare_packet` should not return a valid packet.

**Comment by huitema** [comment]
Calling `prepare_packet` multiple times will not break anything. I find it slightly sub-optimal because it seems better to always process the incoming data. For example, the new data may contain an ACK, and that could spare a retransmit. But doing lots of calls to `prepare_packet` should certainly work.

**Comment by huitema** [comment]
Fixed in PR #465
