### ISSUE TITLE
Support some minimal threading

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#472]
It seems clear that picoquic should be able to run in multi-threaded environment. There are however different level of support:

1) First, probably most useful on clients, is to allow running the application and the transport in different threads. That would require making a series of API calls thread safe: creation of a connection, closing a connection, adding data to a stream, etc. This should apply to all the API calls listed in "picoquic.h".

2) Then, we may consider additional parallelism, maybe managing a thread pool for handling connections, or maybe integrating with an event management API. 

3) We may also consider micro-parallelism for some key operations, such as managing encryption. Could some of that run in a parallel for loop?

Step 2 and 3 are probably only needed for high performance implementations. Step 1 on the other hand seems more urgent, e.g. for developing interactive clients.

**Comment by xdaviddx** [comment]
Yes, step 1 seems very important.  Maybe less so for interactivity of the clients, since they can launch their own separate thread for running the transport and do their own synchronization if multiple non-transport threads need to use the transport for a single endpoint.  However, if they want to communicate with multiple endpoints, how would that be done with the current version of picoquic?  Do they need to synchronize on each API call?  Or on groups of them?

**Comment by huitema** [comment]
Picoquic clients can maintain multiple connections to different servers. The application is currently informed of events by a simple callback API; I suppose that the multi-threaded applications will use these callbacks to send an event to the thread that they want to wake up. The main problem to solve is in the other direction, e.g. to post data in a specific connection context. There are many possible solutions based either on locks or on events; this would be done inside the Picoquic API.

Of course, if you have specific requirements, specs and/or code are welcome!

**Comment by xdaviddx** [comment]
Yes, it is in the context of sending data that I was asking the question.  In the current version of picoquic, if multiple threads in an application would like to send (to one or more endpoints) concurrently, should they ensure that from the first picoquic API call to the last in the sequence of calls needed to prepare and send data that only one of the threads is active?  Or are certain picoquic API calls threadsafe and others aren't?  If it is a subset of calls that aren't threadsafe, and let's say for the sake of the discussion that there are N calls to make to prepare and send data, are there interdependencies (state) between calls such that the calling threads need to ensure they aren't calling a certain group of API calls at the same time.  

I'll illustrate with this and for the sake of the discussion, say there are 6 API calls to make in order to prepare and send data:

function A - thread safe
function B - not thread safe, but isn't sharing any state with another function
function C - thread safe
function D - not thread safe and shares state with D
function E - not thread safe and shares state with C
function F - thread safe

In this scenario, the calling threads:

- Can all call A at the same time
- Have to all synchronize on B, so that they aren't calling B at the same time
- Can all call C at the same time
- Have to all synchronize on D *and* E, so that they aren't calling either in the same time period
- Can all call F at the same time

As you said, having the library itself manage all this is the end game.  I'm asking about the current state.

**Comment by huitema** [comment]
The current state is single threaded. There are a couple of read-only API that are thread safe, but that's about it. The API listed in `picoquic.h` operate at four granularities:

* QUIC context. After setting the parameters, these are API managing packet sending and receiving.

* QUIC connection. Create or close a connection, read or set various parameters.

* QUIC Stream. Send data.

* Callback functions. Operate within the context of the callback.

The first priority is to isolate different connections, so they can accessed from various threads. In that work, the "connection" and "stream" API will thread safe, but would serialized by connection. The context API would only be called from within the context thread.

As you explain, this will have to be documented.

**Comment by xdaviddx** [comment]
Okay, thanks.  If we get into multi-threaded senders before that point in time, we'll just be sure to synchronize on the group of calls from start to finish for sending data, so no two threads try to make any sending API calls at the same time.
