### ISSUE TITLE
How to send 0-RTT packet and add additional HTTP3 header respone

### ISSUE THREAD

**Issue by adikabintang** [private-octopus/picoquic#608]
1. How to send 0-RTT from client side? I tried the `picoquicdemo` and it yields `demo_ticket_store.bin` and `demo_token_store.bin`. Are they supposed to use for resuming the connection using resumption and 0-RTT?

2. I want to add an additional HTTP3 headers: `server`. What I tried was adding:
```
int code = qpack_static[92].index;
qpack_static[92].content = "myserver";
h3zero_qpack_code_encode(bytes, bytes_max, 0xC0, 0x3F, code);
```
in `h3zero_create_response_header_frame` (h3zero.c).

The `qpack_static[92]` is `{ 92, http_header_server, NULL, 0},` in h3zero.c. 

The client only received `server` key without its value `myserver`. So this way must be wrong. How to do it correctly?

**Comment by huitema** [comment]
1) 0-RTT data: if you are using the demo client (picoquicdemo), yes you need to keep the demo_ticket_store.bin and demo_token_store.bin. These files store information about session tickets and connectivity tokens acquired in a run of picoquicdemo. When the client starts, it loads the file content in memory, and checks whether there is a stored session ticket for the specified SNI. If there is one, and if the ticket allows 0-RTT, the client will send the first requests using 0-RTT.

Note that this only works if the command line parameters specify a server name,as in `picoquicdemo example.com 4433`. There is no SNI and thus no 0-RTT if you only specify a server address, as in `picoquicdemo 1.2.3.4 4433`.The workaround is to specify both name and address, as in `picoquicdemo -n example.com 1.2.3.4 4433`.

2) You should use something like:
```
char const *server = "My Server Name";
bytes = h3zero_qpack_literal_plus_ref_encode(bytes, bytes_max, 92, (uint8_t const *)server, strlen(server));
```
Maybe use an `#define H3ZERO_QPACK_SERVER 92` in the header file and use that instead of `92` in the code.

**Comment by adikabintang** [comment]
Nice, thanks. I didn't know that we need to specify server name to have 0-RTT. I have also tried adding HTTP3 header with the way you told me and it worked.
