### ISSUE TITLE
Loss detection bits

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#721]
See 
1. https://tools.ietf.org/html/draft-ferrieuxhamchaoui-quic-lossbits-02

Agreed to develop that using the extensions mechanism; agreed on slack to use TP ID "0x1055" to test the feature, enable it if both ends support the extension. 

Issue: agreement required before any 1RTT packet is sent or received.

**Comment by ferrieux** [comment]
Thanks a lot Christian.
Re "agreement required...":  what's the problem exactly ? aren't TPs exchanged fully within the handshake, so that the first outgoing short header occurs after receiving the TP-0x1055 from the peer, meaning we know exactly what header protection mask to apply and how to fill the loss bits ? Expecting the same logic from the peer, we also know that the first short header we'll receive has been created after receiveing our own TP-0x1055, hence we can compute the proper mask for header deprotection (and RR-bits checking, if needed). What am I missing ?

**Comment by huitema** [comment]
That's just an implementation note, no make sure that we don't run into the issue where the sender sets the bits, but the receiver mistakes that for encrypted bits and the decryption fails. In theory TP negotiation does that, but in practice we need to check.

**Comment by igorlord** [comment]
Per slack conversation, I may prefer TP with separate "allow" (0x01) and "want" (0x02) bits.  That would enable stacks that would not mind allowing the peer to implement the feature but do not want to go into trouble of doing it themselves.

**Comment by huitema** [comment]
Implementation done in PR #724
