### ISSUE TITLE
DoS attack by opening new streams?

### ISSUE THREAD

**Issue by tandf** [private-octopus/picoquic#722]
Hi, I'm an undergraduate student from Tsinghua University. Recently I'm researching picoquic for my thesis, and I have encountered some problems.

I find that in the code, the stream contexts used by callback function are not deleted until the connection is closed. Does that mean an attacker can use up the peer's resource by keeping opening new streams?

But according to the IETF draft, there can be 2^62 streams in one connection. It seems hard to keep tracks of the stream states if the stream contexts are deleted right after it ends, so I'm not sure what is the right thing to do. Also that many streams require lots of resource too. Will this be possible weakness to attacks?

A solution is that the peer should limit streams that a possible attacker can open. But how to tell if the sender is malicious is also a tough question.

It'll be really nice if you can give me a clue. Thanks a lot.

**Comment by huitema** [comment]
I agree that it would be better to free the stream contexts before the end of the connection. This has not been a high priority up to now, but yes, we should do it. As you said, we need to retain knowledge that the stream was created and closed, so it could not be reopened. Since streams are open in order, it is sufficient to retain the largest open stream in each of the 4 contexts. That could be a simple fix.

The number of streams depend of the pattern of the application. Some applications will keep some streams open a long time, other may open one stream per transaction. Each peer can limit the number of streams that the other peer can open, but since this should be decided per application we need some way to express a policy. Maybe something like a stream opening window.

Would you like to propose a code change?

**Comment by tandf** [comment]
Yes I'm really willing to help! But since it's my first time trying to contribute to an open source project, please forgive if I make some mistakes.

You mentioned retaining the largest open stream is enough. But actually I don't think so. From [IETF draft](https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-21.6), it seems when a higher-numbered stream ID is received, the receiver should open all intervening streams.

> Normally, clients will open streams sequentially, as explained in
   Section 2.1.  However, when several streams are initiated at short
   intervals, loss or reordering may cause STREAM frames that open
   streams to be received out of sequence.  On receiving a higher-
   numbered stream ID, a receiver is required to open all intervening
   streams of the same type (see Section 3.2).  Thus, on a new
   connection, opening stream 4000000 opens 1 million and 1 client-
   initiated bidirectional streams.

We have two choices when faced with this situation:
1. create stream context immediately
2. create stream context when a stream of that ID arrives

But neither of them seem good enough. The first one open streams too quick that an attacker can easily force a server to consume memory. The second one requires tracking unopened streams. For example, a possible situation:

![image](https://user-images.githubusercontent.com/25607777/69337241-5f816080-0c9b-11ea-83d7-e942e556a382.png)

Where `x` means close streams, `o` means open streams, `?` means streams that should be opened. High-numbered stream 28, 32, 40 require opening stream 20, 24, 36. If the stream states are discarded once it's closed, we can not tell the difference of close streams and unopen streams.

I see there is a `picoquic_callback_stream_gap` callback event defined but not supported yet. Does it mean to force ordered streams? This can help with this problem, but I'm afraid it's against the spec.

Now the main application for QUIC is HTTP/3 (I think?), and it requires a large number of short lived transactions (again, I think so but I cannot be sure). So maybe we can assume that the application tends to open lots of short-lived streams?

**Comment by huitema** [comment]
@tandf The current code protects against that attack. The number of streams that the peer can create is limited by the parameters `cnx->max_stream_id_bidir_local` and `cnx->max_stream_id_unidir_local`, and these limits apply whether the opening is explicit (new stream) or implicit (streams created because a higher number stream is opened). These variables are updated when MAX STREAM BIDIR or MAX STREAM UNIDIR frames are sent, which happens when the variables `cnx->max_stream_id_bidir_local_computed` or `cnx->max_stream_id_unidir_local_computed` exceed the previously advertised value. The `computed` variables are incremented when streams are closed, i.e. the FIN mark is received and sent, or the stream is reset.

The code is designed so the performance does not degrade significantly if a large number of streams is open -- this was tested by opening 10000 streams, and checking proper performance. I think we measured about 30,000 stream transactions (send GET, receive response) on a loopback connection.

The current stream control logic is implemented in the function `picoquic_prepare_max_streams_frame_if_needed`, and the logic is something like:
```
if current_max - computed > initial_delta/2:
    current_max = current_max + initial_delta
    advertise(current_max)
```
That is, only increment the max stream parameter if only half the current window remains, and in that case increment it by the value set in the initial parameters.

I don't think we have a problem, but we may want to add an API so the application can set the value of "initial_delta" and modify it according to current conditions.

**Comment by huitema** [comment]
The "stream gap" event covers something else -- unreliable streams, used for example to carry video. The gap happens when some data was not received, but because of real time constraints it is better to ignore it than to wait.

**Comment by huitema** [comment]
@tandf I am willing to close this with no action, as the attack is in practice limited by the stream-limit mechanism. On the other hand, you may say that the current code raises the stream limit too quickly, and that the protection is weak. Maybe it should be better controlled by the application. But that seems like a different issue.

**Comment by tandf** [comment]
I think you are right. I'll do some experiments to confirm it's secure when I get my work at hand done.
