### ISSUE TITLE
Coverity issues

### ISSUE THREAD

**Issue by larseggert** [private-octopus/picoquic#855]
I am building picoquic as part of quant (for the h3zero component), and picoquic is therefore run through my CI pipeline.

Coverity finds quite a few issues in picoquic that you might want to look into: https://scan4.coverity.com/reports.htm#v28148/p11628

(Let me know if the link doesn't work for you.)

**Comment by huitema** [comment]
Link doesn't work: 
```
401: Unauthorized

Sorry, your credentials are not valid for this resource. 
```

**Comment by larseggert** [comment]
Figures. I sent you a coverity invite so you can see the quant reports. Let me know if that doesn't work either.

**Comment by huitema** [comment]
Got it, thanks.

**Comment by huitema** [comment]
@larseggert I just checked in PR #858 which should solve most of the issues flagged by coverity, or at least the obvious ones. Some of the issues were typical of this class of program. The code was probably right, but the verifier was confused. I tried to make the program flow more obvious in these cases, but I am not sure that this will make coverity happy.

**Comment by larseggert** [comment]
I’ll let you know when I run it again

**Comment by larseggert** [comment]
I did another run; "2 Newly detected, 22 Eliminated"

**Comment by huitema** [comment]
I am looking at the new results. I need to understand what coverity is really complaining about. For example, I see lots of messages about "casting unsigned int to wider signed int" that I just don't get. For example, I see complaints about constructs like:
```
byte_index + cnx_id_length + 16
```
resulting in "casting to wider int". But in my book, since the first type is `size_t byte_index`, then the expression is supposedly evaluated as size_t. That's what `/usr/local/clang/libexec/ccc-analyzer` believes, in any case.

The difference is probably the level of trust in the compiler. On one hand, `ccc-analyzer` knows what code clang generates, checks the expression, and find it fine. On the other hand, `coverity` is just starting from a theoretical assessment of what the worst compiler could do, and find that there could be some kind of problematic integer casting. But for me that looks a lot like crying wolf...

**Comment by huitema** [comment]
I did a second batch of fixes in PR #860. I think that should do it.

**Comment by larseggert** [comment]
16 is a long constant

**Comment by huitema** [comment]
Mostly fixed, might reopen if there is a new scan.

**Comment by larseggert** [comment]
"1 Newly detected; 7 Eliminated"

**Comment by huitema** [comment]
The new issue was listed because I rolled back a previous fix that caused a crash. It is a red herring. Coverity complains because a file opened in a function is not closed in that function -- but the file handle is kept to be used by the key logging calls. To fix that I would have to reorganize the code so that Coverity understands it, but for me that has no value, just risks.

**Comment by larseggert** [comment]
Odd. I do the same thing in my code and don't get it flagged. Anyway, you're of course free to fix whatever you find most useful.

**Comment by huitema** [comment]
The code was contributed by the wireshark folks. I think coverity is confused because the file is not closed in the same module in which it was created. I could rewrite the code, of course.

**Comment by huitema** [comment]
```
New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)


** CID 357794: Null pointer dereferences (NULL_RETURNS)
/lib/deps/picoquic/picoquic/frames.c: 1560 in picoquic_format_crypto_hs_frame()


________________________________________________________________________________________________________
*** CID 357794: Null pointer dereferences (NULL_RETURNS)
/lib/deps/picoquic/picoquic/frames.c: 1560 in picoquic_format_crypto_hs_frame()
1554 bytes = picoquic_frames_varint_encode(bytes, bytes_max, length);
1555 }
1556 else {
1557 bytes = bytes_l;
1558 }
1559 if (length > 0) {
>>> CID 357794: Null pointer dereferences (NULL_RETURNS)
>>> Dereferencing a pointer that might be "NULL" "bytes" when calling "memcpy". [Note: The source code implementation of the function has been overridden by a builtin model.]
1560 memcpy(bytes, stream->send_queue->bytes + stream->send_queue->offset, length);
1561 bytes += length;
1562 1563 stream->send_queue->offset += length;
1564 if (stream->send_queue->offset >= stream->send_queue->length) {
1565 picoquic_stream_data_node_t* next = stream->send_queue->next_stream_data;
```

**Comment by huitema** [comment]
Fixed.
