### ISSUE TITLE
API to get bandwidth estimate

### ISSUE THREAD

**Issue by fluffy** [private-octopus/picoquic#865]
When sending real time audio and video over QUIC, it would be nice to have and API to get the congestion controllers idea of what  bandwidth is safe to send.

**Comment by huitema** [comment]
There are several congestion control algorithms in picoquic: reno, cubic, bbr. All produce parameters like CWIN, RTT, RTT_MIN; bbr produce a bandwidth estimate and a "rolling" value of RTT_MIN, reset if the min did not decrease for 10 seconds. 

Pacing is implemented as a leaky bucket. All algorithms set a pacing rate and a bucket size.

Providing access to these variables is easy -- they are maintained in the connection context. We could write an accessor if we want to keep the isolation between "public" and "internal" variables.

The accessor would enable the application to poll the current state whenever it wants, but this must be done in the same thread that also runs the protocol to avoid race condition. If synchronization or polling is a problem, we could implement a "pacing updated" call back when the conditions change, and then the application could update its state.

What do you think? Accessor, or callback, or both?

**Comment by fluffy** [comment]
I'd like the data to we get back to be independent of the actually congestion control in use but not sure it matters too much between Accesssor or callback. I'd lean towards callback.

**Comment by huitema** [comment]
What would be the appropriate frequency of the callback?

I have two concerns. First, different algorithms have different timing properties. Reno creates a see-saw pattern with a period growing like the square of the bandwidth, Cubic has raise-flat-test pattern with a period of several RTT, BBR has an 8-RTT pattern of 6 stable period, one test at 25% bandwidth, one recovery at -25% bandwidth. Reno updates congestion parameters on every ACK, Cubic on a time basis, and BBR every 6 to 8 RTT. This could generate very different API behaviors.

Second, these algorithms assume that the application is constantly trying to saturate the connection. That's the only way they can detect a bandwidth increase. But video applications that get a bandwidth estimate from the transport will send at exactly that rate, not faster. That means the algorithms will detect a drop in bandwidth, but not an increase.

Of the three common algorithms, BBR appears much better suited for real time video because it tries to run at the bottleneck bandwidth without adding delays. But it depends on occasional excess traffic to probe for more bandwidth, and that's a gap. That might be compensated by adding better bandwidth probing algorithms, for example based on inter packet arrival time, but that's a research topic.

My gut feeling is to design the API for BBR, and trigger a callback when the estimated bandwidth changes. Then retrofit something for Cubic and Reno. And leave bandwidth probing to the application for now.

**Comment by huitema** [comment]
![image](https://user-images.githubusercontent.com/7464128/77964288-a9a2d000-7293-11ea-8051-f87270fd84c7.png)
This is a quick drawing of the evolution of bandwidth over time with 3 different CC algorithms. Very different patterns.

**Comment by huitema** [comment]
@fluffy do you want to review PR #870 ?

I think that it does what you want.

**Comment by huitema** [comment]
I believe this issue is now solved. PR #870  introduced a set of new API:
```
void picoquic_subscribe_pacing_rate_updates(picoquic_cnx_t* cnx, uint64_t decrease_threshold, uint64_t increase_threshold);
uint64_t picoquic_get_pacing_rate(picoquic_cnx_t* cnx);
uint64_t picoquic_get_cwin(picoquic_cnx_t* cnx);
uint64_t picoquic_get_rtt(picoquic_cnx_t* cnx);
```
And a new callback event:
```
    picoquic_callback_pacing_changed /* Pacing rate for the connection changed */
```
Which together should cover most use cases.
