### ISSUE TITLE
CWIN growth during Slow Start

### ISSUE THREAD

**Issue by madi223** [private-octopus/picoquic#943]
![quic-cwind-loss](https://user-images.githubusercontent.com/66689172/84171946-ac802500-aa7b-11ea-9168-143b0e343f4e.png)

Hello   @ALL, @huitema 

I'm having a strange behavior in QUIC slow start, I don't know whether I should expect this from the SS implementation in picoquic. As you can see in the attached graph, the CWIN grows until 90*Max_datagram_size which is equivalent in my case to at  least 4*BDP since I'm using a 10Mbps link with 25.3ms RTT between picoquicdemo server and client. I first thought it was normal since the ssthresh is supposed to have an infinite value from the beginning of the connection until a loss occurs. Therefore, I introduced some random loss (10%) on the path and I got pretty much the same result, which brought me to wonder whether loss detection is delayed or ignored during SS phase or whether there is a threshold value to hit before switching to Congestion Avoidance Phase.
Is this behavior normal ? (I guess the pacing rate will also increase at the same pace since it is proportional to cwin)

Thanks in advance,
Mamoutou

**Comment by huitema** [comment]
The Reno implementation in Picoquic uses Hystart (same as Cubic), that may explain what you see. The primary benefit of Hystart is to stop sooner, thus overshoot less than pure Reno.

**Comment by madi223** [comment]
> The Reno implementation in Picoquic uses Hystart (same as Cubic), that may explain what you see. The primary benefit of Hystart is to stop sooner, thus overshoot less than pure Reno.

Ok I see. Yes, you're right, this may explain the behavior I'm observing. Just to make sure I understand Hystart the right way, "With a large buffer at the bottleneck link and a large timer threshold for detecting RTT increases in the algorithm, Hystart might be tricked to overshoot more than twice the BDP if the buffer>BDP and the timer threshold is large enough", is that correct ?

**Comment by huitema** [comment]
Hystart normally exits when it sees a significant increase in the RTT, assuming that the delay increase is caused by a queue building up at the bottleneck. For some reason, that detection is happening late in your setup, and a large queue is allowed to build up.

I don't know exactly why. I can speculate, but I would rather analyze traces. Could you turn on the collection of binary traces on the client and server side, as explained above, and send me the capture files `server_log.bin` and `client_log.bin`?

**Comment by huitema** [comment]
@madi223 Any further data on this?

**Comment by madi223** [comment]
> @madi223 Any further data on this?

@huitema , please find attached the binary log files for the server and the client.
I also uploaded the qlog version of the 2 logs on https://qvis.edm.uhasselt.be but I didn't see a graph representing cwin growth (maybe I didn't look at the right menu). In the csv format, we have cwin as well as send_mtu, the graph I sent earlier was derived using cwin/send_mtu in the csv log. You'll aslo find attached the resulting file. Thanks again @huitema . I'll let you know as soon as I find new hints/data. Thanks
[cwin_growth.txt](https://github.com/private-octopus/picoquic/files/4781617/cwin_growth.txt)




[quic-log.tar.gz](https://github.com/private-octopus/picoquic/files/4781523/quic-log.tar.gz)

**Comment by huitema** [comment]
Thanks for the files, @madi223! You probably did not see the congestion graph because you submitted the client's log. The `picolog` program creates a file named after the initial CID -- same value for client and server. To save 2 files, you need to save client and server in different folders. I understand that's not intuitive...
![image](https://user-images.githubusercontent.com/7464128/84689073-42d99e00-aef5-11ea-80c4-45aab7514704.png)
In any case, I extracted the server file and got the congestion graph. This is an extract, focusing on the beginning of the connection. In this case, the RTT starts increasing at T=130. However, the RTT increase is modest, from 25ms to just over 30 ms, and the Picoquic implementation of Hystart does not react immediately. The first packet loss is observed at T=166, at which point the Reno behavior kicks in, halving the window. The window will be halved again at T=195 and T=223.

I see that for the whole session the measured RTT never exceeds 35 ms, while the min RTT is 25 ms. It would be indicative of a rather small buffer in the router, well below the bandwidth delay product. Are you configuring that on purpose?

**Comment by madi223** [comment]
> Thanks for the files, @madi223! You probably did not see the congestion graph because you submitted the client's log. The `picolog` program creates a file named after the initial CID -- same value for client and server. To save 2 files, you need to save client and server in different folders. I understand that's not intuitive...
> ![image](https://user-images.githubusercontent.com/7464128/84689073-42d99e00-aef5-11ea-80c4-45aab7514704.png)
> In any case, I extracted the server file and got the congestion graph. This is an extract, focusing on the beginning of the connection. In this case, the RTT starts increasing at T=130. However, the RTT increase is modest, from 25ms to just over 30 ms, and the Picoquic implementation of Hystart does not react immediately. The first packet loss is observed at T=166, at which point the Reno behavior kicks in, halving the window. The window will be halved again at T=195 and T=223.
> 
> I see that for the whole session the measured RTT never exceeds 35 ms, while the min RTT is 25 ms. It would be indicative of a rather small buffer in the router, well below the bandwidth delay product. Are you configuring that on purpose?

**Comment by madi223** [comment]
Thanks for your clear analysis @huitema . Very helpful. Yes, I set the bottleneck buffer to a small value on purpose (BDP/4). Actually, I'm comparing QUIC and TCP under different network conditions (buffer size, loss rate, delay etc.). In this scenario, besides setting a small buffer size, I also set packet loss to 10% (random loss). In TCP, the first loss is detected at the beginning of slow start hence it enters congestion avoidance early which can explain why picoquic is better than TCP in this particular setting. I didn't observe cwin growth in the other scenarios though ( when buffer=BDP or BDP/2), I should do that in order to observe Hystart behavior globally. Thanks to your analysis, now I have a rather clear picture of what is going on, but I just wonder why the detection of the first loss is delayed compared to TCP, maybe it has to do with QUIC loss detection based on packet threshold and timeout rather than duplicate ACKs (although they are quite similar)

**Comment by madi223** [comment]
@huitema , could you tell me what version of picoquic you are using ? In my version, the congestion algorithm is specified using -G instead of -g option and log conversion is done using picolog_t.

**Comment by huitema** [comment]
Sorry. I am doing a lot of this work on Windows, and the logging app on Windows is "picolog.exe". It is indeed "picolog_t" on Unix. And the option is "-G".

Quic does not really do dupack, because the packet sequence numbers are monotonically increasing. It uses the RACK logic to detect holes. The latest version of Picoquic has been updated to tighten that logic (PR #952).

The shallow buffer test is interesting. Maybe I should add that to the test suite. What would be the success criteria?

**Comment by madi223** [comment]
Ok, I see.

 In my case the shallow buffer test was just to compare QUIC and TCP under unusual network conditions. I'd say the success criteria will be a faster loss detection than TCP because I think QUIC doesn't need to wait for may RTTs before declaring a packet lost even while using very small buffer since it doesn't rely on dupACKs ( but packet number threshold).  Actually, my assumption was:  Since QUIC is supposed to have an improved recovery mechanism (thanks to RACK like logic, SACK logic etc. according to draft-28, ), QUIC (reno) should outperform TCP(reno) under high loss (due to random loss or queue drops) but apparently, it is not really the case from what I'm seeing in my test results. TCP Reno outperforms QUIC in terms of goodput (large file download) whether in ideal conditions (buffer=BDP loss=0%) or in unusual conditions (buffer=BDP/4 loss=4%). However, QUIC slightly outperforms TCP only when buffer=BDP/4 and loss=10% which is a very uncommon use case. In order to make sense of my results, I looked at older QUIC drafts, especially QUIC-recovery-00 where I read that the ACK train detection is disabled in QUIC Hystart because of QUIC pacing , so I suppose QUIC relies only on RTT increases in order to determine ssthresh during the slow start (I guess you used the same logic in picoquic). In the latest drafts (27 and 28), I looked at how pacing is performed but it doesn't give deep details, I wonder if QUIC could be throughput limited depending on the pacer logic. Is the pacing implemented in picoquic follows the leaky bucket logic? is the pacing rate updated by a bandwidth estimator ? 

Thanks

**Comment by huitema** [comment]
Just a word of caution: you are preparing a study comparing "QUIC" and "TCP", but you are really comparing "an implementation of QUIC" (Picoquic) and "an implementation of TCP". Details of loss recovery or pacing can vary a lot between implementations.

In theory, the loss recovery and congestion control for QUIC is specified in the "recovery" draft (https://tools.ietf.org/html/draft-ietf-quic-recovery), but the congestion control part of this draft is really a place holder. The WG charter mandated that the WG should only work on the New Reno algorithm, so that's what the draft says. However, almost no implementation is shipping with Reno, due to know performance problems under either high losses or long BDP, as obvious from the early work by Mathis et al. (http://ccr.sigcomm.org/archive/1997/jul97/ccr-9707-mathis.pdf). Implementations typically use Cubic or BBR.

I wonder whether your experimentation shows a weakness in Picoquic's implementation of loss detection. You mention dupack. The equivalent in QUIC would be detection of gaps in the ACK sequence. There is a tension there between detecting losses as soon as a gap is noticed and being robust to packet reordering in the network. In order to support reordering, Picoquic will only act on a gap if it is not corrected after some delay, currently RTT/4. There may be a need to tune that.

Pacing uses a leaky bucket algorithm. When using Reno, the pacing rate is derived from the CWIN and the SRTT.

**Comment by madi223** [comment]
Thanks @huitema for all this valuable information and links. You're right, It would make more sense to do studies/comparisons based on implementations. When I said Reno, I was referring to new Reno, sorry. From your explanation, I can see now pretty much the logic behind the implemented loss detection mechanism, and as you mentioned it makes sense since reordering is covered as well. 

As for the  picoquic loss detection robustness, I think, I need to run more tests before concluding. It's getting more and more interesting so I'll continue testing the loss detection aspect until I can make a good conclusion :) .

For the pacing, I guess the pacing rate formula  is  kind of similar to the specification in  https://tools.ietf.org/html/draft-ietf-quic-recovery : rate = N * congestion_window / smoothed_rtt. I'll look at the source code in order to get more details about the implementation of pacing at different level (Slow start, Congestion avoidance etc.). 

Thanks

**Comment by huitema** [comment]
The current loss detection does not decide based on packet numbers. Maybe it should maintain a "max reordering distance" initially set to some standard value, and dynamically updated. That requires keeping track of the loss detection decision for each retransmitted packet, and doing an adaptation:

1) If spurious transmission is detected and the decision was based on reordering distance, increase the max reordering distance.
2) If there is no spurious detection detected after a long enough timer and decision was based on reordering distance, confirm that the distance is adequate or maybe a bit small.

The same logic could be applied to a max reordering timer or a max retransmission timer. But before doing that I would probably need some modeling and some measurements on real networks. From anecdotal evidence, we see two kind of sources for reordering:

1) Some routers put the short packets in front of the transmit queue, in an attempt to improve performance of latency sensitive apps like telnet or VOIP or timeliness of TCP ACKs.

2) Some path do Equal-Cost Multipath Load Balancing, but the multiple paths may have slightly different actual delays.

Maybe I need to simulate that...

**Comment by madi223** [comment]
Hello @huitema , I'm actually having trouble with qvis vizualization tool. the tool doesn't print CWND and RTT graph, all it does is to show the graph in picture below although I'm sure I correctly extracted the log from the server. 
![qvis-screen](https://user-images.githubusercontent.com/66689172/86943672-06d9d780-c147-11ea-87a5-7d26bda0c27f.png)

Please find attached the qlog file returned by picolog_t command, do I need to change something in the file so that qvis can draw CWND graph ?

Thanks in advance
[server.qlog.zip](https://github.com/private-octopus/picoquic/files/4891921/server.qlog.zip)

**Comment by huitema** [comment]
I do not find the "metrics updated" events in your qlog file. That's very strange. If you still have the binlog , can you run 
```
picolog_t -f csv -o <your_folder> <your_binlog_file>
```
Or, if you prefer, just send me a copy of the binlog file? I would like to understand why the CWND and RTT updates are not written to the qlog.

**Comment by madi223** [comment]
Ok, I've run the command, please find attached the 2 files.
Maybe the picolog_t version I'm using is too old (maybe I have to pull the latest changes).

Thanks @huitema 
[server_log.tar.gz](https://github.com/private-octopus/picoquic/files/4895428/server_log.tar.gz)

**Comment by huitema** [comment]
I suspect that's the problem. My version of picolog cannot parse the bin file that you sent. Best practice would be to load the latest version of picoquic and compile both picoquicdemo and picolog.

**Comment by madi223** [comment]
@huitema 

You were right, after recompiling picolog and picoquicdemo with the latest changes I was able to get a good qlog file. Now everything is OK (I can see CWND growth in qvis).

Thanks
