### ISSUE TITLE
Transmission of dummy data

### ISSUE THREAD

**Issue by AbhishiktaP** [private-octopus/picoquic#980]
Can we send our dummy data like images or videos or even text files on picoquic? If yes, where can we edit the code to do the same?

**Comment by huitema** [comment]
When you mention dummy data, are you thinking of for example JPG files with random images, or TXT files with random content? The simplest solution by far would be to create these files in the folder served by the server. For example, if you launch the server as:
```
picoquicdemo -w dummy_data_folder -p 4433
```
Then the server will automatically serve any file in the folder -- provided of course that the client asks for it.

Is that what you need?

**Comment by huitema** [comment]
Otherwise, the next simple solution is to use the "post" API. This is defined in "demoserver.h":
```
typedef int (*picohttp_post_data_cb_fn)(picoquic_cnx_t* cnx,
    uint8_t* bytes, size_t length,
    picohttp_call_back_event_t fin_or_event, struct st_picohttp_server_stream_ctx_t* stream_ctx);

/* Define the table of special-purpose paths used for POST or REST queries */
typedef struct st_picohttp_server_path_item_t {
    char* path;
    size_t path_length;
    picohttp_post_data_cb_fn path_callback;
} picohttp_server_path_item_t;

typedef struct st_picohttp_server_parameters_t {
    char const* web_folder;
    picohttp_server_path_item_t* path_table;
    size_t path_table_nb;
} picohttp_server_parameters_t;
```
And can be used when initializing the path context to associate a particular "path" in the name space supported by the server with a callback function provided by the user. For an example, you can look at the unit tests `h3zero_post_test()` and `h09_post_test()` in `h3zerotest.c`. You will have to insert the code in the server initialization in `picoquicdemo.c`, at the beginning of the `int quic_server()` code: create the callback functions, document the path items, and include the pointers in the element `picoquic_file_param` before the call to `picoquic_create`.

**Comment by AbhishiktaP** [comment]
Thank you! I will try it out
