### ISSUE TITLE
Should we remove the binlog intermediary and standardize on qlog?

### ISSUE THREAD

**Issue by huitema** [private-octopus/picoquic#981]
The story of logging in picoquic is a bit long. It started with a semi formal test log, then added an ad hoc binary log to capture congestion control and recovery issues. Both were upgraded over time. During that time, the qlog effort started by Robin Marx took off, and is becoming a standard. The first reaction was to add the picolog program that derives a set of qlog from the binary log, which was good but leads to multiple logging formats. There are also three specific issues:

1) The qlog are extracted when the server has finished the connection. But during the interop runner tests there is no way to run the picolog command just after that, prevented automated post processing.

2) On a running server, the binary log runs forever and the disk eventually fills up. File swap strategies could work, e.g. close the file when it has reached some size and open a new one. But with these strategies connections that overlap the swap would be split over two binary log, or maybe many logs for long running connections.

3) There are often needs to add data to the log. But the binary log format is not easily extensible. This creates a dependency between the version of picoquic used to capture the file and the version of picolog used to extract the qlog.

The proposal is to remove the binary log, and have picoquic directly write qlog files. Clients and servers would be parameterized with a folder name, in which they would create one qlog file per connection. This solves the 3 issues above:

1) The qlog will be available immediately, as soon as the connection closes, much like the text log currently is.

2) On the server, we can use a cron job to archive or delete old qlog files, thus ensuring that the disk does not fill up.

3) If picoquic is updated to produce new data, the updated qlog becomes immediately available for the newly captured connections, but the old qlog files captured previously can still be used -- they just won't have the newly added data.

Since the qlog contains as much data as the text log, this would allow us to remove the text log, and achieve the unified logging mentioned in issue #811.

The main drawback is that removing the binlog prevents other uses of the binlog data, such as extracting CSV files for visualizing congestion issues or drawing SVG visualizations directly from the binlog, as envisaged by @steschu77. The CSV file is a weak argument, because QVIS visualization of qlog files is more effective to debug congestion issues. I think that SVG visualizations could also be achieved by using the qlog as a source -- qvis does that, and  the [qlogstat](https://github.com/private-octopus/qlogstats/) project shows that qlog files can be parsed easily.

I would like to hear advice from current users, especially @steschu77 and @madi223.

**Comment by madi223** [comment]
@huitema 

I think qlog files would be enough to draw and visualize most relevant information (whether using qvis or a self-maid script). before using qvis I was using my own python scipt to visualize data from the generated csv file but as you mentioned, this could be easily done by parsing the qlog file. From my point of view generating directly a qlog file is pretty convenient (since it already contains everything and it also removes the dependency struggle between different picolog versions), besides, it is well-structured data model that is gaining popularity.
Thanks

**Comment by steschu77** [comment]
I wouldn't mind losing the CSV and SVG visualization since QVIS does a great job as well in that regard.

I am a little bit outdated with regard to QUIC's recent developments but at the time of building the binary logging approach it was not clear for the very first packets to which connection they would belong to. I remember trying to have a binary log file per connection but this wasn't possible because you'd miss the first packets. You would face the same issue with a QLOG file per connection written at real-time. You could achieve point 1 and 2 just by doing that again and write a binary log file per connection. I wouldn't conflate this issue with a switch to another format.

The other reason for me to favor the binary log over QLOG was performance. The logging should be as less overhead as possible and since QUIC packets are already also very structured binary data, that seemed to be a simple format for logging. I remember that the implementation as I left it reconstructs these packets before writing them but the goal was to just write what is received and sent with a little header.

The next reason for the binary logging was software complexity. As I mentioned above, the idea was to write the same format that QUIC defines, just adding a little extra header such that other meta information can be logged as well. That would keep the core library of picoquic small and simple and extra complexity added by QLOG or whatever format could be added as separate libraries.

I don't understand your third point, @huitema, since the binary log was also built with extensibility in mind and with new chunk types you could add new data and you also can use old files with newer versions of the converter as long as you don't change existing chunk types. Changes in the QUIC packets themselves are indeed a problem, I agree. For this kind of backward compatibility you need to define another invariant, i.e. the thing that will not change across versions. This could be QLOG but my assumption was that QUIC has been finalized enough to be this invariant.

**Comment by huitema** [comment]
@steschu77 The performance issue is real. QLOG files are bigger than binary files, that means more disk writing. On the other hand, filling up the disk is also a performance issue, and it is much easier to address with "log files per connection" than with "common log file". Plus, in the environments were you do need the qlog, you are going to spend the cost on your server anyhow -- outside of the picoquic process, but still on the server CPU. In fact, you will spend more CPU in that case: first doing the binary log, then also doing the qlog.

I think the performance impact can be mitigated otherwise. We have three levels today: no logging, logging of the first 100 packets, logging of the full connection. We might add a fourth option, logging of a fraction of connections, say 1%. This will allow busy servers to get some logs and investigate potential issues, without incurring a huge cost for the average connection.

The extension problem happens in practice when people do not update picoquicdemo and picolog at the same time, or when they want to reprocess old binary logs with the new version of picolog. Not a huge issue, but still an issue.

Yes, there is an issue with packets processed outside of a connection context. On the server side, an example would be the "retry" process -- initial packet arrives, server rejects it with a retry message. We need a solution there, ideally such that the retry exchange and the subsequent connection are logged in the same qlog file. Then there is version negotiation, which is probably less urgent. There is also the "stateless reset" process, which is not tied to a connection context on the server side; it is a DDOS protection measure, so we have to be cautious. And there are also packets that get rejected because of wrong keys, or coding errors. For those too, I am worried about DDOS resistance. But on the other hand, when debugging, it is really useful to understand that the server considered a packet erroneous. In the current version, picolog produces a separate qlog file for each of these packets, based on the DCID. That's probably not ideal.

**Comment by steschu77** [comment]
I understand the wish to get a QLOG file immediately once a connection is closed and likely we will get there. But as mentioned earlier I would not switch the format and do connection based logging at the same time as they are two separate issues and should also be discussed separately.

The connection based logging can already be implemented with the binary logging given the limitations you outlined, i.e. no "retry" or "stateless reset" being logged in the connection based log file.

Once that works, you can still switch to a QLOG format.

Regarding your note on performance, I see two use cases. First, the one you mention where all binary logs are converted into QLOG format for further investigation. The other use case would be logging everything and only convert the logs for connections that really had an issue. The latter one should still be a bit less CPU and disk consuming when done with binary logs.

On the other hand, if you require logs on such detailed level on your server, you should also be willing to spend the extra cost.

**Comment by huitema** [comment]
@steschu77 If I summarize your proposal, you will proceed in two steps instead of one. The first step would be to keep producing binary, but instead of producing just one single log file, create one for each connection. We could have an additional option in that step, to convert the binary to qlog immediately upon connection close if that's what the local user or admin desires.. Maybe run the conversion in a background thread so that it does not make the servers unresponsive. The second step would be to create the qlog directly, but we could do that later, when we have resolved the issues around out-of-connection login. 

The big advantage would be limited code change -- writing a direct qlog logger requires jettisoning and rewriting much of the existing binary logging and qlog conversion, and that's not great. The first step also gives us most of the usability benefits of the full qlog conversion, especially if we complement it by in-process conversion. The second step would just be a trade-off between performance and code re-use.

I agree with you, let's do this first step first, and get experience with the single-file-per-connection issues.

**Comment by steschu77** [comment]
I opened a PR with changes for per connection logging, but I could use some help fixing the broken tests :)
https://github.com/private-octopus/picoquic/pull/986

Also, please check if the limitations of this approach would not impose any issues:
* Some app messages are context free (i.e. use `picoquic_log_context_free_app_message` instead of `picoquic_log_app_message` for logging)
* There is no state-less packet logging any more

**Comment by huitema** [comment]
We can do a second PR once we have a proper design for context free logging. Putting that in the text log for now is expedient. The alternative would be to change the way context free events are logged -- for several of them, there might be a way to associate the event with a context if the event is logged at a different place in the code. Comments in the PR about the broken tests.

**Comment by huitema** [comment]
Solved with PR #986 and PR #987.
